## Máquina para testes
Vagrant.configure("2") do |config|
  config.vm.hostname = "devops-challenge"
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.56.4"
  config.vm.provider "virtualbox" do |vb|
	vb.memory = "2048"
	vb.cpus = "2"
	vb.name = "devops-challenge"
  end
end
