---
- hosts: vagrant-machine
  become: yes
  tasks:

  - name: Instala dependencias do docker
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present

  - name: Adiciona chave GPG
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
  
  - name: Adiciona repositório
    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

  - name: Atualiza Pacotes
    apt:
      update_cache: yes

  - name: Instala Docker 
    apt:
      pkg:
        - docker
        - docker-compose
      state: present

  - name: Baixando Docker-compose versão 1.29
    shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  
  - name: Habilitando docker-compose
    shell: chmod +x /usr/local/bin/docker-compose

        
  - name: Iniciando projeto com docker-compose up -d
    shell: docker-compose up -d
    args:
      chdir: /srv/challenge
